---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Сайт должен иметь логотип, название и контактную информацию магазина
  - Сайт должен иметь систему регистрации и авторизации пользователей, а также возможность восстановления пароля
  - Сайт должен иметь систему отзывов и рейтингов товаров, а также возможность сравнения товаров
  - Сайт должен иметь систему уведомлений и подписки на новости и акции магазина
  - Сайт должен иметь систему оплаты и доставки товаров, а также возможность отслеживания статуса заказа
